POST http://localhost:3000/criar__conta
Content-Type: application/json

{
    "nome": "JacyelGamer24",
    "email": "id",
    "senha": "123456"
}

###

POST http://localhost:3000/enviar__mensagem
Content-Type: application/json

{
    "id": "coloque um id de usuário",
    "texto": "Testando 123"
}

###
GET http://localhost:3000/pegar__mensagens?id_user=id

###
GET http://localhost:3000/pegar__midia__mensagens?id=coloque aqui o id da mensagem

###
GET http://localhost:3000/pegar__mensagens?id_user=coloque aqui o id de um usuario

### Enviar comentarios

POST http://localhost:3000/enviar_comentarios
Content-Type: application/json

{
    "id_mensagem": "cmcngq9vq0002uptoh6qgwdrm",
    "texto": "Eai blz"
}

### Pegar comentários

GET http://localhost:3000/pegar__nome?id=id

### Deletar conta

DELETE http://localhost:3000/deletar__conta?id=id

### Pegar nome com email
GET http://localhost:3000/pegar__nome__usuario__comentario?email=email

### Da like
POST http://localhost:3000/curtir__mensagem
Content-Type: application/json

{
    "id_msg": "id",
    "id_user": "id"
}